### ISSUE TITLE
NPM Install fails

### ISSUE THREAD

**Issue by mushon** [daat-hamakom/maps#21]
Error:

`ERROR in ./~/css-loader!./~/sass-loader?includePaths[]=/Users/mushon/sites/daat-maps/maps/~/node-bourbon/~/bourbon/app/assets/stylesheets!./src/styles/app.scss
Module build failed: ReferenceError: Promise is not defined
    at LazyResult.async (/Users/mushon/sites/daat-maps/maps/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:157:31)
    at LazyResult.then (/Users/mushon/sites/daat-maps/maps/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:79:21)
    at processCss (/Users/mushon/sites/daat-maps/maps/node_modules/css-loader/lib/processCss.js:198:5)
    at Object.module.exports (/Users/mushon/sites/daat-maps/maps/node_modules/css-loader/lib/loader.js:24:2)
 @ ./src/styles/app.scss 4:14-240
`

**Comment by yuvadm** [comment]
Which node/NPM versions do you have? Upgrade so something new-ish and you'll be fine.

**Comment by mushon** [comment]
npm@1.4.3

**Comment by yuvadm** [comment]
Yeah, ante up :)

**Comment by mushon** [comment]
Ante up?

**Comment by yuvadm** [comment]
Install a modern NPM version
